version: '3'

services:
  todofront:
    image: todofrontend
    ports:
      - 3000:3000
    enviroment:
      - REACT_APP_API_HOST=todoback
    depends_on:
      - todoback

  todoback:
    image: todobackend
    ports:
      - 3001:3001

  todotests:
    image: todotests
    enviroment:
      - FRONT_HOST=todofront
    depends_on:
      - todofront
      - todoback
